// flow-typed signature: f0cc850a050cfefb7eb9b498bc93abc1
// flow-typed version: <<STUB>>/react-spring_v^9.0.0-rc.3/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spring/konva.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/konva' {
  declare module.exports: any;
}

declare module 'react-spring/native.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/native' {
  declare module.exports: any;
}

declare module 'react-spring/three.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/three' {
  declare module.exports: any;
}

declare module 'react-spring/universal.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/universal' {
  declare module.exports: any;
}

declare module 'react-spring/web.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/web' {
  declare module.exports: any;
}

declare module 'react-spring/zdog.cjs' {
  declare module.exports: any;
}

declare module 'react-spring/zdog' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spring/konva.cjs.js' {
  declare module.exports: $Exports<'react-spring/konva.cjs'>;
}
declare module 'react-spring/konva.js' {
  declare module.exports: $Exports<'react-spring/konva'>;
}
declare module 'react-spring/native.cjs.js' {
  declare module.exports: $Exports<'react-spring/native.cjs'>;
}
declare module 'react-spring/native.js' {
  declare module.exports: $Exports<'react-spring/native'>;
}
declare module 'react-spring/three.cjs.js' {
  declare module.exports: $Exports<'react-spring/three.cjs'>;
}
declare module 'react-spring/three.js' {
  declare module.exports: $Exports<'react-spring/three'>;
}
declare module 'react-spring/universal.cjs.js' {
  declare module.exports: $Exports<'react-spring/universal.cjs'>;
}
declare module 'react-spring/universal.js' {
  declare module.exports: $Exports<'react-spring/universal'>;
}
declare module 'react-spring/web.cjs.js' {
  declare module.exports: $Exports<'react-spring/web.cjs'>;
}
declare module 'react-spring/web.js' {
  declare module.exports: $Exports<'react-spring/web'>;
}
declare module 'react-spring/zdog.cjs.js' {
  declare module.exports: $Exports<'react-spring/zdog.cjs'>;
}
declare module 'react-spring/zdog.js' {
  declare module.exports: $Exports<'react-spring/zdog'>;
}
