// flow-typed signature: 6f94a5d16a16de111725cf0bae63a002
// flow-typed version: <<STUB>>/react-use-gesture_v^7.0.16/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-use-gesture'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-use-gesture' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-use-gesture/dist' {
  declare module.exports: any;
}

declare module 'react-use-gesture/dist/react-use-gesture.cjs.development' {
  declare module.exports: any;
}

declare module 'react-use-gesture/dist/react-use-gesture.cjs.production.min' {
  declare module.exports: any;
}

declare module 'react-use-gesture/dist/react-use-gesture.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-use-gesture/dist/index' {
  declare module.exports: $Exports<'react-use-gesture/dist'>;
}
declare module 'react-use-gesture/dist/index.js' {
  declare module.exports: $Exports<'react-use-gesture/dist'>;
}
declare module 'react-use-gesture/dist/react-use-gesture.cjs.development.js' {
  declare module.exports: $Exports<'react-use-gesture/dist/react-use-gesture.cjs.development'>;
}
declare module 'react-use-gesture/dist/react-use-gesture.cjs.production.min.js' {
  declare module.exports: $Exports<'react-use-gesture/dist/react-use-gesture.cjs.production.min'>;
}
declare module 'react-use-gesture/dist/react-use-gesture.esm.js' {
  declare module.exports: $Exports<'react-use-gesture/dist/react-use-gesture.esm'>;
}
